--CRIAR A TABELA DE 'ENDERECO'
CREATE TABLE ENDERECO(
	ID				INT				IDENTITY(1,1),
	LOGRADOURO		VARCHAR(150)	NOT NULL,
	COMPLEMENTO		VARCHAR(50)		NOT NULL,
	NUMERO			VARCHAR(50)		NOT NULL,
	BAIRRO			VARCHAR(50)		NOT NULL,
	LOCALIDADE		VARCHAR(50)		NOT NULL,
	UF				VARCHAR(2)		NOT NULL,
	CEP				VARCHAR(10)		NOT NULL,
	PRIMARY KEY(ID));
GO

--CRIAR A TABELA DE 'CLIENTE'
CREATE TABLE CLIENTE(
	ID				INT				IDENTITY(1,1),
	NOME			VARCHAR(150)	NOT NULL,
	CPF				VARCHAR(14)		NOT NULL,
	DATANASCIMENTO	DATE			NOT NULL,
	ENDERECO_ID		INT				NOT NULL UNIQUE,
	PRIMARY KEY(ID),
	FOREIGN KEY(ENDERECO_ID) REFERENCES ENDERECO(ID));
GO